name: sample-nodejs

services:
- environment_slug: node-js
  http_port: 19000
  github:
    branch: develop
    deploy_on_push: true
    repo: https://github.com/hiveopolis/hiveopolis-beeapp
  name: sample-nodejs